//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalprojectmulti_tier.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDiagram
    {
        public string Name { get; set; }
        public int Principal_id { get; set; }
        public int Diagram_id { get; set; }
        public string Version { get; set; }
        public string Definition { get; set; }
    }
}
